"""added relationshsips to User Order OrderProduct 

Revision ID: 3a2fc532009f
Revises: 4db68e0b5695
Create Date: 2024-02-25 15:20:34.958104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2fc532009f'
down_revision = '4db68e0b5695'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
