"""added relationshsips to User Order OrderProduct3 

Revision ID: 3ff60a9683e9
Revises: 3a2fc532009f
Create Date: 2024-02-25 15:25:05.254172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff60a9683e9'
down_revision = '3a2fc532009f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
