"""Another Initial migration

Revision ID: 4db68e0b5695
Revises: c0867c689f22
Create Date: 2024-02-23 15:17:07.627804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db68e0b5695'
down_revision = 'c0867c689f22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
