"""dropped my_new_table

Revision ID: 4f23d60b8a5d
Revises: c60c12c99b22
Create Date: 2024-02-21 13:57:02.014255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f23d60b8a5d'
down_revision = 'c60c12c99b22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
