"""changed username -> user_name

Revision ID: 5a93a4a574a0
Revises: 4bda9386a893
Create Date: 2024-02-23 14:16:13.945898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a93a4a574a0'
down_revision = '4bda9386a893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username', new_column_name='user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username', new_column_name='user_name')
    # ### end Alembic commands ###
