"""changed products and users

Revision ID: beb91908ea91
Revises: 4f23d60b8a5d
Create Date: 2024-02-21 14:14:39.269620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb91908ea91'
down_revision = '4f23d60b8a5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language_code', type_=sa.VARCHAR(10), nullable=False)
    op.alter_column('users', 'username', new_column_name='user_name')

    op.add_column('products', sa.Column('price', sa.DECIMAL(precision=16, scale=4), nullable=False))
    op.alter_column('products', 'description', type_=sa.VARCHAR(3000))
    # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('products', 'description',
#                     type_=sa.VARCHAR(), nullable=True)
#     op.drop_column('products', 'price')
#     op.alter_column('users', 'language_code',
#                     type_=sa.VARCHAR(255), nullable=False)
#     op.alter_column('users', 'user_name', new_column_name='username')
    # ### end Alembic commands ###
